default_deploy_mode = "ctf"

[build]
build_mode = "arena"

[ctf]
destination = "/Users/username/ScreepsArena"
prune = false
branch = "alpha-capture_the_flag"
  [ctf.build]
  extra_options = ["--features=arena-capture-the-flag"]

[swamp]
destination = "/Users/username/ScreepsArena"
prune = false
branch = "alpha-spawn_and_swamp"
  [swamp.build]
  extra_options = ["--features=arena-spawn-and-swamp"]

[collect]
destination = "/Users/username/ScreepsArena"
prune = false
branch = "alpha-collect_and_control"
  [collect.build]
  extra_options = ["--features=arena-collect-and-control"]

# for full syntax, see
# https://github.com/rustyscreeps/cargo-screeps/blob/master/screeps-defaults.toml